### ISSUE TITLE
Automatically pull workshop data from AMY

### ISSUE THREAD

**Issue by jezcope** [LibraryCarpentry/lc-second-website#45]
The [Software Carpentry]() and [Data Carpentry]() websites pull workshop data automatically from [AMY](), or possibly AMY pushes it in. Either way, we should do this too.

The current website already generates the workshops page from a static data file in the same format so hopefully it's just a case of hooking it all up.

**Comment by fmichonneau** [comment]
What's your timeline for the new website release? I can set you up with the
automated workshop feed as you're getting to make the website public.

**Comment by weaverbel** [comment]
The website is public now @fmichonneau but there has been an issue of under-reporting of LC workshops because many of the earlier ones were not listed in AMY so we have not switched over to an automatic feed as this would under-report what we have done. Our manual `yaml` allows us to have a complete list so we still use this to make the feed to our site. Now that we have begun to record LC workshops in AMY, we could think about closing off this way of working and leaving it as our "past workshops" list and then generate the AMY feed for all new workshops going forward. We need to loop in @libcce and possibly Maneesha and Sher! as they have themost up to date knowledge of how far along we are with recording LC workshops in AMY. 

I do think it would be nice to have the Carpentries-style, AMY-generated workshop feed with the maps etc. What do you think @jezcope ? @libcce?

**Comment by libcce** [comment]
I absolutely agree that we should move to a feed from AMY. As @weaverbel mentions, if we did this now, we wouldn't be capturing all the workshops as some of the workshops we list on the LC site are Carpentries-inspired but not official workshops. As part of our incubation as a lesson organization, this is one of the items that we need to address, and in our discussions, Maneesha, Sher, Tracy, Belinda, this is our end goal to not have this be a manual process. In early October, we will presenting LC's response to The Carpentries incubation conditions and much of that will be tied to the new website @weaverbel and I have been working on. I'd like for an automated feed of workshops to be a part of the website launch but it is too soon to confirm. All I can say is that it is at the top of the list at the moment.

**Comment by weaverbel** [comment]
What do you think of my idea to keep and use the `yaml` to list past workshops but then use AMY from then on @libcce?

Also for those who may not be aware Chris and I are looking at using a different website template as the current template does not allow us to easily add new pages and we are starting to need more and more pages as we grow and develop.

**Comment by libcce** [comment]
@weaverbel I'm hoping we can enter all of our workshops in AMY, past, present, and future. This might require some DB development as part of our incubation process. I can add the past workshops to AMY, we just need to know how LC-inspired workshops will be entered.

**Comment by jduckles** [comment]
I recommend you add all past workshops to AMY as they will be then counted as part of programatic assessments, otherwise they won't be.

**Comment by libcce** [comment]
Moved to https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/1
